### ISSUE TITLE
Pick a database price-quality

### ISSUE THREAD

**Issue by ichhrak** [Capstone-Project-SEG/AIChatbotSystem#5]
- Research different Pricing Tiers for using MongoDB on Microsoft Azure. 
- Pick the best and most logical Tier.

**Comment by Hasanalyabroudi** [comment]
https://docs.google.com/document/d/1ZKpZMNlC15s6-hCbS-ecjt8ew96zD2jKA90nOEVHjks/edit?usp=sharing
